### ISSUE TITLE
Support changing password via api

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl-users#9]
Currently, admins can new Users and set their passwords using the api, but not update existing User passwords. This ticket covers adding support for updating User passwords using the api

**Comment by janeeisenstein** [comment]
Implemented in 0.7.8 and 0.8.?

**Comment by fcurella** [comment]
Would initiating a password reset for the user (rather than set their password explicitly) work for your use case? I'm worried about the security implications of sending the password around in, eg: email or other means.

**Comment by janeeisenstein** [comment]
This functionality is needed to support changing passwords programmatically outside of Django Admin. The 'admin' initiating these requests will be SIMPL_GAMES_AUTH.
